//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursa4.Entitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long ID { get; set; }
        public long Order { get; set; }
        public long Product { get; set; }
        public int Count { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
