//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursa4.Entitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeta
    {
        public long ID { get; set; }
        public long User { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
